version: "3.8"

services:
  mongodb:
    build: ./db
    env_file: .env
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null 
    environment:
      - MONGODB_USER=${MONGODB_USER:-uajuser}
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    env_file: .env
    build: ./api-server
    restart: unless-stopped
    ports:
      - $API_HOST_PORT:$API_CONTAINER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=${MONGODB_USER:-uaj_user}
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=${MONGODB_DATABASE:-uaj_telemetry_db}
      - DB_PORT=${MONGODB_CONTAINER_PORT:-27017}
    stdin_open: true
    tty: true

volumes:
  db: